"""
AI Examiner for Prompt Doctor.
Evaluates user prompts against level-specific prompt engineering principles
and returns structured JSON verdicts.
"""

import os
import json
import re
import requests
from dotenv import load_dotenv

load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "deepseek/deepseek-chat")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")


EXAMINER_SYSTEM_PROMPT = """You are a friendly but fair prompt-engineering examiner. Be encouraging but ensure students demonstrate the level's core concepts.

Your role is to evaluate if the student's prompt demonstrates the CURRENT LEVEL's principles. Be reasonable but enforce level requirements.

## Rules
1. Judge ONLY the current level's principles - verify they are actually present in the prompt.
2. Check if the principle is demonstrated in the PROMPT itself, not just if the output happens to be correct.
3. For each principle, verify it exists in the student's prompt before marking it as pass.
4. Be lenient on perfection, but strict on presence - the concept must be attempted.
5. Ask exactly ONE helpful guiding question per failed principle.
6. NEVER rewrite the student's prompt or provide corrections.
7. Return JSON only — no additional text, no markdown, no code blocks.

## Output Schema
{
  "level": <integer>,
  "principles": [
    {
      "name": "<principle name>",
      "pass": <true or false>,
      "weakness": "<what's missing from the prompt>",
      "question": "<one helpful question>"
    }
  ],
  "ran_ok": true,
  "verdict": "pass" or "revise"
}

## Evaluation Guidelines by Level

**Level 1 - Basic Prompting:**
- Check if prompt assigns a role (e.g., "You are a...") 
- Check if instructions are clear and specific
- Check if output format is mentioned
- Pass if: All 3 elements are present, even if basic

**Level 2 - Structured Output:**
- Check if prompt explicitly requests JSON format
- Check if prompt defines specific fields/schema
- Check if model output is valid, parseable JSON
- Pass if: Prompt mentions JSON + defines fields + output is valid JSON

**Level 3 - Few-Shot Prompting:**
- Check if prompt contains at least 1-2 concrete examples
- Examples must show input → output pattern
- Check if examples help clarify the task
- Pass if: Prompt has clear examples AND output correctly applies the pattern

**Level 4 - Reasoning:**
- Check if prompt explicitly asks for step-by-step reasoning
- Check if prompt breaks task into logical steps
- Check if output shows reasoning process
- Pass if: Prompt requests reasoning/steps AND output demonstrates it

**Level 5 - Robustness:**
- Check if prompt has defensive instructions (ignore X, only focus on Y)
- Check if prompt handles edge cases/adversarial input
- Check if output remains correct despite noisy input
- Pass if: Prompt has defensive instructions AND output is correct

## Verdict Logic
- "pass": ALL level principles are demonstrated in the prompt AND output is appropriate
- "revise": If ANY principle is missing or not demonstrated in the prompt

Be fair but firm - students must show they understand and implemented the level's concept.

## Input Format
{
  "level": <number>,
  "principles": [<strings>],
  "student_prompt": "<text>",
  "sample_input": "<text>",
  "model_output": "<text>"
}
"""


def grade_prompt(level, principles, student_prompt, sample_input, model_output):
    """
    Grade a user's prompt using the AI examiner.

    Args:
        level: Current level number (1-5)
        principles: List of principle strings to evaluate
        student_prompt: The user's written prompt
        sample_input: The sample input data
        model_output: The output generated by running the prompt

    Returns:
        dict with the examiner's verdict (see spec for schema)
    """
    if not OPENROUTER_API_KEY or OPENROUTER_API_KEY == "your_openrouter_api_key_here":
        return {
            "level": level,
            "principles": [
                {
                    "name": p,
                    "pass": False,
                    "weakness": "API key not configured.",
                    "question": "Please set OPENROUTER_API_KEY in .env file.",
                }
                for p in principles
            ],
            "ran_ok": False,
            "verdict": "revise",
        }

    examiner_input = {
        "level": level,
        "principles": principles,
        "student_prompt": student_prompt,
        "sample_input": sample_input,
        "model_output": model_output,
    }

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://prompt-doctor.app",
        "X-Title": "Prompt Doctor",
    }

    payload = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {"role": "system", "content": EXAMINER_SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(examiner_input, indent=2)},
        ],
        "temperature": 0.4,  # Balanced for fair but consistent grading
        "max_tokens": 2048,
    }

    try:
        response = requests.post(
            f"{OPENROUTER_BASE_URL}/chat/completions",
            headers=headers,
            json=payload,
            timeout=60,
        )
        response.raise_for_status()
        data = response.json()

        if "choices" in data and len(data["choices"]) > 0:
            content = data["choices"][0]["message"]["content"]
            return _parse_examiner_response(content, level, principles)
        else:
            return _fallback_verdict(level, principles, "Empty API response")

    except requests.exceptions.Timeout:
        return _fallback_verdict(level, principles, "Request timed out")
    except requests.exceptions.RequestException as e:
        error_msg = str(e)
        try:
            error_data = e.response.json() if e.response else {}
            if "error" in error_data:
                error_msg = error_data["error"].get("message", str(e))
        except (ValueError, AttributeError):
            pass
        return _fallback_verdict(level, principles, f"API error: {error_msg}")
    except Exception as e:
        return _fallback_verdict(level, principles, f"Unexpected error: {str(e)}")


def _parse_examiner_response(content, level, principles):
    """
    Parse the examiner's response, extracting JSON from it.
    Handles cases where the model wraps JSON in markdown code blocks.
    """
    # Try to extract JSON from markdown code blocks first
    json_match = re.search(r"```(?:json)?\s*([\s\S]*?)```", content)
    if json_match:
        json_str = json_match.group(1).strip()
    else:
        json_str = content.strip()

    # Try to find JSON object in the response
    try:
        # Find the first { and last }
        start = json_str.find("{")
        end = json_str.rfind("}")
        if start != -1 and end != -1:
            json_str = json_str[start : end + 1]

        result = json.loads(json_str)

        # Validate and normalize the response
        if "principles" not in result:
            result["principles"] = [
                {
                    "name": p,
                    "pass": False,
                    "weakness": "Examiner did not evaluate this principle.",
                    "question": "Review the principle and revise your prompt.",
                }
                for p in principles
            ]

        # Ensure all principles are present
        existing_names = {p["name"] for p in result["principles"]}
        for p in principles:
            if p not in existing_names:
                result["principles"].append(
                    {
                        "name": p,
                        "pass": False,
                        "weakness": "Not evaluated by examiner.",
                        "question": "Ensure your prompt addresses this principle.",
                    }
                )

        # Normalize principle fields
        for p in result["principles"]:
            if "weakness" not in p:
                p["weakness"] = "" if p.get("pass") else "No specific feedback."
            if "question" not in p:
                p["question"] = "" if p.get("pass") else "Review and revise your prompt."

        # Determine verdict
        all_pass = all(p.get("pass", False) for p in result["principles"])
        result["verdict"] = "pass" if all_pass else "revise"
        result["level"] = level
        result["ran_ok"] = True

        return result

    except (json.JSONDecodeError, ValueError) as e:
        # If parsing fails, return a fallback verdict
        return _fallback_verdict(
            level, principles, f"Could not parse examiner response: {str(e)}"
        )


def _fallback_verdict(level, principles, error_reason):
    """Generate a fallback verdict when the examiner fails."""
    return {
        "level": level,
        "principles": [
            {
                "name": p,
                "pass": False,
                "weakness": f"Examiner error: {error_reason}",
                "question": "Please try submitting again.",
            }
            for p in principles
        ],
        "ran_ok": False,
        "verdict": "revise",
    }